### ISSUE TITLE
Invalid Credential 

### ISSUE THREAD

**Issue by IbrahemSabbah** [dineshshetty/Android-InsecureBankv2#11]
the server is running on port 8888 and return invalid credentials.

I use below users:
dinesh/Dinesh@123$
jack/Jack@123$

**Comment by dineshshetty** [comment]
Just cloned the repo and tried it - it works. Sure you are following the guide? Have you set up the IP address in prefs? Is machine-machine access allowed on your network? Firewall disabled?

Open netcat on your machine and then adb into your emulator. Try to connect to the address from adb and see if you can reach the machine. This is clearly a network issue on your side and sadly not something I can fix.

<img width="843" alt="works" src="https://user-images.githubusercontent.com/2169995/31054312-3cbea718-a67e-11e7-84c1-8401dabb32d4.png">

**Comment by IbrahemSabbah** [comment]
this from terminal 
<img width="1440" alt="screen shot 2017-10-01 at 4 15 40 pm" src="https://user-images.githubusercontent.com/5676201/31054843-e2472562-a6c3-11e7-92e1-8ea735841bcd.png">
