### ISSUE TITLE
Is there interest for a StaCoAn tutorial?

### ISSUE THREAD

**Issue by vincentcox** [dineshshetty/Android-InsecureBankv2#13]
I saw this project flying by on twitter. Looks really interesting and I will use it for testing my project [StaCoAn](https://github.com/vincentcox/StaCoAn). If there is interest, I can make a tutorial on how to use StaCoAn with this project?

**Comment by dineshshetty** [comment]
Sure. Go ahead. :)

**Comment by vincentcox** [comment]
Thanks, will write this week a tutorial and add it to this repo. 💪
