### ISSUE TITLE
Server IP address not being saved

### ISSUE THREAD

**Issue by mohsin2928** [dineshshetty/Android-InsecureBankv2#14]
hi , while using this app I am trying to save the save server IP in the  preferences and I get the message that server configured successfully whether the ip add is right or wrong, and while going back to recheck the preferences the server IP column is blank,and while i use the user name and password provided and click on sign in nothing happens,i have tried it on different geny motions models and restarted the devices as well as pc and i am not using any proxy,currently i am using SONTOKU OS platform and genymotion emulator as well 
![1](https://user-images.githubusercontent.com/44868349/48556601-7c9b8a80-e8f5-11e8-9438-72425d3d3545.JPG)

**Comment by mohsin2928** [comment]
any update on this ?

**Comment by Nageshvs11** [comment]
I am also facing the same issue?
can some one please help to fix this issue.

**Comment by dineshshetty** [comment]
It is just the way the UI works. The changes are always stored on the device once you change the IP address. To confirm take a look at the local sharedpref file.
