### ISSUE TITLE
AVD creation per Usage Guide PDF

### ISSUE THREAD

**Issue by martialhax** [dineshshetty/Android-InsecureBankv2#16]
Hi Dinesh,

Any way to get the Usage Guide updated before the Black Hat USA course?
It's a pre-req listed and I got it working but not through workflow listed using downloaded plain SDK. The steps don't match/work anymore. Creating the AVD through Android Studio works however its not a rooted AVD instance. The app screams as much when launching it in the launched Studio emulator.

Thank you! Much appreciated.

**Comment by dineshshetty** [comment]
Yea, we'll be sending a followup email to all the attendees more than a
month before the course with all the pre-req information. I'll be updating
the app with some more stuff before that.

Cheers

**Comment by martialhax** [comment]
Thanks much appreciated.
