### ISSUE TITLE
not able to login with default credentails

### ISSUE THREAD

**Issue by APOORVMAGAN** [dineshshetty/Android-InsecureBankv2#2]
![insecank1](https://cloud.githubusercontent.com/assets/14202709/14073275/517141ee-f4e5-11e5-9437-b4546963ec24.png)

**Comment by dineshshetty** [comment]
Are you sure you are entering the right credentials? I confirmed this again and it works for me and everyone else.
Proof:
<img width="538" alt="db_browser_for_sqlite_-__users_dns_desktop_android-insecurebankv2_androlabserver_mydb_db" src="https://cloud.githubusercontent.com/assets/2169995/14304474/fe60e052-fb80-11e5-9725-d555aebdf2b8.png">
