### ISSUE TITLE
Proxying Android Traffic - ProxyDroid app

### ISSUE THREAD

**Issue by evidi** [dineshshetty/Android-InsecureBankv2#27]
Hi! I am trying to download and install ProxyDroid on android emulator but I can't find a compatible app. So far, I have tried to install from apkmirror and apkpure version 3.2.0 and 2.7.7 but I get the error "adb: failed to install ProxyDroid_v2.7.7_apkpure.com.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]"

**Comment by evidi** [comment]
I found an apk compatible to my AVD but once I am opening, the app stops and asks me to force stop.

**Comment by dineshshetty** [comment]
You can use the standard wifi options on the emulator to proxy the traffic
