### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by noama163** [dineshshetty/Android-InsecureBankv2#30]
Hi Can I get help ?

Tried doing the:

sudo -H pip3 install --upgrade cheroot still not working 

Tracback Error
 File app.py line 6 in <module>
  from cheroot import esgi 
Import Error no module named cheroot

**Comment by sirmalware** [comment]
run via python2 worked for me

**Comment by Adreeta16** [comment]
How did you solve it ? 
When I am running app.py it shows :
from cheroot import wsgi # This replaces the 2 above
ImportError:No module named cheroot 

But when I ran requirements.txt . All the requirements were installed.

**Comment by sirmalware** [comment]
sudo -H pip install cheroot
