### ISSUE TITLE
newer Cherrypy (10.X) not working

### ISSUE THREAD

**Issue by anantshri** [dineshshetty/Android-InsecureBankv2#4]
the latest version of cherrypi is not working with the androlab server.

```
Android-InsecureBankv2/AndroLabServer> pip list --format=legacy| grep Cherry          
CherryPy (10.0.0)
Android-InsecureBankv2/AndroLabServer> python app.py 
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from cherrypy import wsgiserver
ImportError: cannot import name wsgiserver
```
while downgrading to cherrypy 5.1.0 does works.

So you might want to update the code or clarify in requirement's that only cherrypy 5.1.0 works with this. which effectively means we need to use virtualenv for this package as not everyone would prefer keeping system wide older version of cherrypy.

**Comment by dineshshetty** [comment]
Fixed in the latest commit.
