### ISSUE TITLE
Login credential

### ISSUE THREAD

**Issue by mk2011sharma** [dineshshetty/Android-InsecureBankv2#8]
Hi Dinesh,
I am using it on santoku machine but unable to login with the mentioned credentials. Andro server is runnig,I have tried on both v1,v2
Username: dinesh
password: Dinesh@123$
or 
Username:jack
password:Jack@123$

Application throws a pop invalid credentials .Is there any other credentials available for this one .

**Comment by omerlh** [comment]
Take a look at the Android logs, it happens to me because the application was not connected to the server.

**Comment by dineshshetty** [comment]
Are you sure that the AndroLabServer is running? Do you get invalid credentials error on the server logs?

**Comment by alliejk** [comment]
I have a same problem:( server works and shows port num 8888 but cannot login with the credentials. Also, server doesn't show any error logs. I think server is not properly working, but don't know how to fix... please let me know

**Comment by dineshshetty** [comment]
Just cloned the repo and tried it - it works. Sure you are following the guide? Have you set up the IP address in prefs? Is machine-machine access allowed on your network? Firewall disabled?

Open netcat on your machine and then adb into your emulator. Try to connect to the address from adb and see if you can reach the machine. This is clearly a network issue on your side and sadly not something I can fix.

<img width="843" alt="works" src="https://user-images.githubusercontent.com/2169995/31054312-3cbea718-a67e-11e7-84c1-8401dabb32d4.png">

**Comment by ethicalhackingplayground** [comment]
What version of python should I use?

**Comment by Anjali0077** [comment]
> What version of python should I use? it comes up with an error.
> 
> "Traceback (most recent call last): File "app.py", line 2, in import web ImportError: No module named web"

use python -m pip install -r requirements.txt
      python app.py
